apiVersion: v1
kind: Pod
metadata:
  name: log-app
  labels:
    app: log-app
spec:
  containers:
  - name: log-app
    image: busybox
    args:
    - /bin/sh
    - -c
    - >
      i=0;
      while true;
      do
        echo "$i: $(date)" >> /var/log/1.log;
        echo "$(date) INFO $i" >> /var/log/2.log;
        i=$((i+1));
        sleep 1;
      done
    volumeMounts:
    - name: log-storage
      mountPath: /var/log
  - name: sidecar-log-collector
    image: jungoproazuredevops.azurecr.io/fluent-bit-tail:0.0.2
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
    volumeMounts:
    - name: log-storage
      readOnly: true
      mountPath: /var/log
  volumes:
  - name: log-storage
    emptyDir: {}